[package]
name = "lcov-parser"
version = "0.4.0"
keywords = [ "parser", "LCOV", "report", "code-coverage" ]
description = "LCOV report parser for Rust"
authors = ["holyshared <holy.shared.design@gmail.com>"]
license = "MIT"
repository = "https://github.com/holyshared/lcov-parser"
readme = "README.md"

[dependencies]
parser-combinators = "0.5.1"
lines = "0.0.3"
